### ISSUE TITLE
Can not communicate with server in port 3001 the default one

### ISSUE THREAD

**Issue by meera-m-t** [lanquarden/pyScrcClient#2]
Hello,

I tried to run your code 
```{bash}
python pyclient.py   --track Alaborg --stage 2 --id sameerah --port 3001
```
```{bash}
Sending init string to server: sameerah(init -90 -75 -60 -45 -30 -20 -15 -10 -5 0 5 10 15 20 30 45 60 75 90)
didn't get response from server...
Sending id to server:  sameerah
Sending init string to server: sameerah(init -90 -75 -60 -45 -30 -20 -15 -10 -5 0 5 10 15 20 30 45 60 75 90)
didn't get response from server...
Sending id to server:  sameerah
Sending init string to server: sameerah(init -90 -75 -60 -45 -30 -20 -15 -10 -5 0 5 10 15 20 30 45 60 75 90)
didn't get response from server...
Sending id to server:  sameerah
Sending init string to server: sameerah(init -90 -75 -60 -45 -30 -20 -15 -10 -5 0 5 10 15 20 30 45 60 75 90)
```
Here are the install steps I followed:
1. Installed torcs and started the engine.
2. The engine doesn't recogonize any ID I send.

**Comment by lanquarden** [comment]
Hi,

this is code dating back quite a few years and haven't maintained it since. I did a quick search though and found these:

- https://github.com/mpvharmelen/torcs-client
- https://github.com/moltob/pytocl
- https://github.com/joramwessels/torcs-client

These are all based on my original code but will be a lot more up to date.

Happy coding!
